services:
  - type: web
    name: flask-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:10000 app:app"
    plan: free
    envVars:
      - key: PORT
        value: 10000
